-- Crear un esquema si no existe
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'ejercicio_2_dbo')
BEGIN
    EXEC('CREATE SCHEMA ejercicio_2_dbo')
END
GO

USE DB_lh_prodriguez;

CREATE TABLE [ejercicio_2_dbo].[TBL_AFILIACION](
	[ID_AFILIACION] [bigint] IDENTITY(1,1) NOT NULL,
	[PERSONA_ID] [bigint] NOT NULL,
	[ES_TRABAJADOR] [bit] NOT NULL,
	[ES_JUBILADO] [bit] NOT NULL,
	[DESCUENTO_RENTA] [int] NULL,
 CONSTRAINT [PK_TBL_AFILIACION] PRIMARY KEY CLUSTERED
(
	[ID_AFILIACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [ejercicio_2_dbo].[TBL_CREDITO]    Script Date: 10/3/2023 8:17:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ejercicio_2_dbo].[TBL_CREDITO](
	[ID_CREDITO] [bigint] IDENTITY(1,1) NOT NULL,
	[PERSONA_ID] [bigint] NOT NULL,
	[TIPO_CREDITO_ID] [bigint] NOT NULL,
	[MONTO] [int] NOT NULL,
	[FECHA_SOLICITUD] [date] NOT NULL,
	[ESTADO] [bit] NOT NULL,
	[ES_EN_LINEA] [bit] NOT NULL,
	[PROMOTOR_ID] [bigint] NULL,
 CONSTRAINT [PK_TBL_CREDITO] PRIMARY KEY CLUSTERED
(
	[ID_CREDITO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [ejercicio_2_dbo].[TBL_PERSONA]    Script Date: 10/3/2023 8:17:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ejercicio_2_dbo].[TBL_PERSONA](
	[ID_PERSONA] [bigint] IDENTITY(1,1) NOT NULL,
	[RUT] [nvarchar](12) NOT NULL,
	[NOMBRE] [nvarchar](50) NOT NULL,
	[APELLIDO_PATERNO] [nvarchar](50) NOT NULL,
	[APELLIDO_MATERNO] [nvarchar](50) NOT NULL,
	[CORREO_ELECTRONICO] [nvarchar](50) NOT NULL,
	[TELEFONO] [nvarchar](50) NOT NULL,
	[DIRECCION_PARTICULAR] [nvarchar](50) NOT NULL,
	[DIRECCION_LABORAL] [nvarchar](50) NOT NULL,
	[NIVEL_INGRESOS] [int] NOT NULL,
	[NIVEL_ENDEUDAMIENTO] [int] NOT NULL,
 CONSTRAINT [PK_TBL_PERSONA] PRIMARY KEY CLUSTERED
(
	[ID_PERSONA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [ejercicio_2_dbo].[TBL_PROMOTOR]    Script Date: 10/3/2023 8:17:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ejercicio_2_dbo].[TBL_PROMOTOR](
	[ID_PROMOTOR] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](50) NOT NULL,
	[APELLIDO_PATERNO] [nvarchar](50) NOT NULL,
	[APELLIDO_MATERNO] [nvarchar](50) NOT NULL,
	[SUCURSAL_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_TBL_PROMOTOR] PRIMARY KEY CLUSTERED
(
	[ID_PROMOTOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [ejercicio_2_dbo].[TBL_SUCURSAL]    Script Date: 10/3/2023 8:17:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ejercicio_2_dbo].[TBL_SUCURSAL](
	[ID_SUCURSAL] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](50) NOT NULL,
	[DIRECCION] [nvarchar](50) NOT NULL,
	[REGION] [nvarchar](50) NOT NULL,
	[CIUDAD] [nvarchar](50) NOT NULL,
	[COMUNA] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TBL_SUCURSAL] PRIMARY KEY CLUSTERED
(
	[ID_SUCURSAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [ejercicio_2_dbo].[TBL_TIPO_CREDITO]    Script Date: 10/3/2023 8:17:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ejercicio_2_dbo].[TBL_TIPO_CREDITO](
	[ID_TIPO_CREDITO] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TBL_TIPO_CREDITO] PRIMARY KEY CLUSTERED
(
	[ID_TIPO_CREDITO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [ejercicio_2_dbo].[TBL_CREDITO] ADD  CONSTRAINT [DF_TBL_CREDITO_FECHA_SOLICITUD]  DEFAULT (getdate()) FOR [FECHA_SOLICITUD]
GO
ALTER TABLE [ejercicio_2_dbo].[TBL_AFILIACION]  WITH CHECK ADD  CONSTRAINT [FK_TBL_AFILIACION_TBL_PERSONA] FOREIGN KEY([PERSONA_ID])
REFERENCES [ejercicio_2_dbo].[TBL_PERSONA] ([ID_PERSONA])
GO
ALTER TABLE [ejercicio_2_dbo].[TBL_AFILIACION] CHECK CONSTRAINT [FK_TBL_AFILIACION_TBL_PERSONA]
GO
ALTER TABLE [ejercicio_2_dbo].[TBL_CREDITO]  WITH CHECK ADD  CONSTRAINT [FK_TBL_CREDITO_TBL_PERSONA] FOREIGN KEY([PERSONA_ID])
REFERENCES [ejercicio_2_dbo].[TBL_PERSONA] ([ID_PERSONA])
GO
ALTER TABLE [ejercicio_2_dbo].[TBL_CREDITO] CHECK CONSTRAINT [FK_TBL_CREDITO_TBL_PERSONA]
GO
ALTER TABLE [ejercicio_2_dbo].[TBL_CREDITO]  WITH CHECK ADD  CONSTRAINT [FK_TBL_CREDITO_TBL_PROMOTOR] FOREIGN KEY([PROMOTOR_ID])
REFERENCES [ejercicio_2_dbo].[TBL_PROMOTOR] ([ID_PROMOTOR])
GO
ALTER TABLE [ejercicio_2_dbo].[TBL_CREDITO] CHECK CONSTRAINT [FK_TBL_CREDITO_TBL_PROMOTOR]
GO
ALTER TABLE [ejercicio_2_dbo].[TBL_CREDITO]  WITH CHECK ADD  CONSTRAINT [FK_TBL_CREDITO_TBL_TIPO_CREDITO] FOREIGN KEY([TIPO_CREDITO_ID])
REFERENCES [ejercicio_2_dbo].[TBL_TIPO_CREDITO] ([ID_TIPO_CREDITO])
GO
ALTER TABLE [ejercicio_2_dbo].[TBL_CREDITO] CHECK CONSTRAINT [FK_TBL_CREDITO_TBL_TIPO_CREDITO]
GO
ALTER TABLE [ejercicio_2_dbo].[TBL_PROMOTOR]  WITH CHECK ADD  CONSTRAINT [FK_TBL_PROMOTOR_TBL_SUCURSAL] FOREIGN KEY([SUCURSAL_ID])
REFERENCES [ejercicio_2_dbo].[TBL_SUCURSAL] ([ID_SUCURSAL])
GO
ALTER TABLE [ejercicio_2_dbo].[TBL_PROMOTOR] CHECK CONSTRAINT [FK_TBL_PROMOTOR_TBL_SUCURSAL]
GO




